sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t arielvolnicher/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true arielvolnicher/docker-react npm run test